/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAliadosIndexRouteImport } from './routes/_authenticated/aliados/index'
import { Route as AuthenticatedAliadosIdRouteImport } from './routes/_authenticated/aliados/$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAliadosIndexRoute =
  AuthenticatedAliadosIndexRouteImport.update({
    id: '/aliados/',
    path: '/aliados/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAliadosIdRoute = AuthenticatedAliadosIdRouteImport.update({
  id: '/aliados/$id',
  path: '/aliados/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aliados/$id': typeof AuthenticatedAliadosIdRoute
  '/aliados/': typeof AuthenticatedAliadosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aliados/$id': typeof AuthenticatedAliadosIdRoute
  '/aliados': typeof AuthenticatedAliadosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/aliados/$id': typeof AuthenticatedAliadosIdRoute
  '/_authenticated/aliados/': typeof AuthenticatedAliadosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/aliados/$id' | '/aliados/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/aliados/$id' | '/aliados'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/aliados/$id'
    | '/_authenticated/aliados/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/aliados/': {
      id: '/_authenticated/aliados/'
      path: '/aliados'
      fullPath: '/aliados/'
      preLoaderRoute: typeof AuthenticatedAliadosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aliados/$id': {
      id: '/_authenticated/aliados/$id'
      path: '/aliados/$id'
      fullPath: '/aliados/$id'
      preLoaderRoute: typeof AuthenticatedAliadosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAliadosIdRoute: typeof AuthenticatedAliadosIdRoute
  AuthenticatedAliadosIndexRoute: typeof AuthenticatedAliadosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAliadosIdRoute: AuthenticatedAliadosIdRoute,
  AuthenticatedAliadosIndexRoute: AuthenticatedAliadosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
