/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedDescuentosRouteImport } from './routes/_authenticated/descuentos'
import { Route as AuthenticatedAliadosIndexRouteImport } from './routes/_authenticated/aliados/index'
import { Route as AuthenticatedAlianzasDescuentosRouteImport } from './routes/_authenticated/alianzas/descuentos'
import { Route as AuthenticatedAliadosIdRouteImport } from './routes/_authenticated/aliados/$id'
import { Route as AuthenticatedRelacionesInternacionalesIndicadoresIndexRouteImport } from './routes/_authenticated/relaciones-internacionales/indicadores/index'
import { Route as AuthenticatedRelacionesInternacionalesAliadosIndexRouteImport } from './routes/_authenticated/relaciones-internacionales/aliados/index'
import { Route as AuthenticatedProyeccionIndicadoresIndexRouteImport } from './routes/_authenticated/proyeccion/indicadores/index'
import { Route as AuthenticatedProyeccionAliadosIndexRouteImport } from './routes/_authenticated/proyeccion/aliados/index'
import { Route as AuthenticatedInvestigacionIndicadoresIndexRouteImport } from './routes/_authenticated/investigacion/indicadores/index'
import { Route as AuthenticatedInvestigacionAliadosIndexRouteImport } from './routes/_authenticated/investigacion/aliados/index'
import { Route as AuthenticatedDecanaturasIndicadoresIndexRouteImport } from './routes/_authenticated/decanaturas/indicadores/index'
import { Route as AuthenticatedDecanaturasAliadosIndexRouteImport } from './routes/_authenticated/decanaturas/aliados/index'
import { Route as AuthenticatedAlianzasIndicadoresIndexRouteImport } from './routes/_authenticated/alianzas/indicadores/index'
import { Route as AuthenticatedAlianzasAliadosIndexRouteImport } from './routes/_authenticated/alianzas/aliados/index'
import { Route as AuthenticatedRelacionesInternacionalesAliadosIdRouteImport } from './routes/_authenticated/relaciones-internacionales/aliados/$id'
import { Route as AuthenticatedProyeccionAliadosIdRouteImport } from './routes/_authenticated/proyeccion/aliados/$id'
import { Route as AuthenticatedInvestigacionAliadosIdRouteImport } from './routes/_authenticated/investigacion/aliados/$id'
import { Route as AuthenticatedDecanaturasAliadosIdRouteImport } from './routes/_authenticated/decanaturas/aliados/$id'
import { Route as AuthenticatedAlianzasAliadosIdRouteImport } from './routes/_authenticated/alianzas/aliados/$id'
import { Route as AuthenticatedDecanaturasSocialesAliadosIndexRouteImport } from './routes/_authenticated/decanaturas/sociales/aliados/index'
import { Route as AuthenticatedDecanaturasSaludAliadosIndexRouteImport } from './routes/_authenticated/decanaturas/salud/aliados/index'
import { Route as AuthenticatedDecanaturasIngenieriasAliadosIndexRouteImport } from './routes/_authenticated/decanaturas/ingenierias/aliados/index'
import { Route as AuthenticatedAlianzasProyectosAliadosIndexRouteImport } from './routes/_authenticated/alianzas/proyectos/aliados/index'
import { Route as AuthenticatedAlianzasMercadeoAliadosIndexRouteImport } from './routes/_authenticated/alianzas/mercadeo/aliados/index'
import { Route as AuthenticatedAlianzasGraduadosAliadosIndexRouteImport } from './routes/_authenticated/alianzas/graduados/aliados/index'
import { Route as AuthenticatedAlianzasEcontiAliadosIndexRouteImport } from './routes/_authenticated/alianzas/econti/aliados/index'
import { Route as AuthenticatedDecanaturasSocialesAliadosIdRouteImport } from './routes/_authenticated/decanaturas/sociales/aliados/$id'
import { Route as AuthenticatedDecanaturasSaludAliadosIdRouteImport } from './routes/_authenticated/decanaturas/salud/aliados/$id'
import { Route as AuthenticatedDecanaturasIngenieriasAliadosIdRouteImport } from './routes/_authenticated/decanaturas/ingenierias/aliados/$id'
import { Route as AuthenticatedAlianzasProyectosAliadosIdRouteImport } from './routes/_authenticated/alianzas/proyectos/aliados/$id'
import { Route as AuthenticatedAlianzasMercadeoAliadosIdRouteImport } from './routes/_authenticated/alianzas/mercadeo/aliados/$id'
import { Route as AuthenticatedAlianzasGraduadosAliadosIdRouteImport } from './routes/_authenticated/alianzas/graduados/aliados/$id'
import { Route as AuthenticatedAlianzasEcontiAliadosIdRouteImport } from './routes/_authenticated/alianzas/econti/aliados/$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDescuentosRoute = AuthenticatedDescuentosRouteImport.update({
  id: '/descuentos',
  path: '/descuentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAliadosIndexRoute =
  AuthenticatedAliadosIndexRouteImport.update({
    id: '/aliados/',
    path: '/aliados/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlianzasDescuentosRoute =
  AuthenticatedAlianzasDescuentosRouteImport.update({
    id: '/alianzas/descuentos',
    path: '/alianzas/descuentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAliadosIdRoute = AuthenticatedAliadosIdRouteImport.update({
  id: '/aliados/$id',
  path: '/aliados/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelacionesInternacionalesIndicadoresIndexRoute =
  AuthenticatedRelacionesInternacionalesIndicadoresIndexRouteImport.update({
    id: '/relaciones-internacionales/indicadores/',
    path: '/relaciones-internacionales/indicadores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelacionesInternacionalesAliadosIndexRoute =
  AuthenticatedRelacionesInternacionalesAliadosIndexRouteImport.update({
    id: '/relaciones-internacionales/aliados/',
    path: '/relaciones-internacionales/aliados/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProyeccionIndicadoresIndexRoute =
  AuthenticatedProyeccionIndicadoresIndexRouteImport.update({
    id: '/proyeccion/indicadores/',
    path: '/proyeccion/indicadores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProyeccionAliadosIndexRoute =
  AuthenticatedProyeccionAliadosIndexRouteImport.update({
    id: '/proyeccion/aliados/',
    path: '/proyeccion/aliados/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestigacionIndicadoresIndexRoute =
  AuthenticatedInvestigacionIndicadoresIndexRouteImport.update({
    id: '/investigacion/indicadores/',
    path: '/investigacion/indicadores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestigacionAliadosIndexRoute =
  AuthenticatedInvestigacionAliadosIndexRouteImport.update({
    id: '/investigacion/aliados/',
    path: '/investigacion/aliados/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDecanaturasIndicadoresIndexRoute =
  AuthenticatedDecanaturasIndicadoresIndexRouteImport.update({
    id: '/decanaturas/indicadores/',
    path: '/decanaturas/indicadores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDecanaturasAliadosIndexRoute =
  AuthenticatedDecanaturasAliadosIndexRouteImport.update({
    id: '/decanaturas/aliados/',
    path: '/decanaturas/aliados/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlianzasIndicadoresIndexRoute =
  AuthenticatedAlianzasIndicadoresIndexRouteImport.update({
    id: '/alianzas/indicadores/',
    path: '/alianzas/indicadores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlianzasAliadosIndexRoute =
  AuthenticatedAlianzasAliadosIndexRouteImport.update({
    id: '/alianzas/aliados/',
    path: '/alianzas/aliados/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelacionesInternacionalesAliadosIdRoute =
  AuthenticatedRelacionesInternacionalesAliadosIdRouteImport.update({
    id: '/relaciones-internacionales/aliados/$id',
    path: '/relaciones-internacionales/aliados/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProyeccionAliadosIdRoute =
  AuthenticatedProyeccionAliadosIdRouteImport.update({
    id: '/proyeccion/aliados/$id',
    path: '/proyeccion/aliados/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestigacionAliadosIdRoute =
  AuthenticatedInvestigacionAliadosIdRouteImport.update({
    id: '/investigacion/aliados/$id',
    path: '/investigacion/aliados/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDecanaturasAliadosIdRoute =
  AuthenticatedDecanaturasAliadosIdRouteImport.update({
    id: '/decanaturas/aliados/$id',
    path: '/decanaturas/aliados/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlianzasAliadosIdRoute =
  AuthenticatedAlianzasAliadosIdRouteImport.update({
    id: '/alianzas/aliados/$id',
    path: '/alianzas/aliados/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDecanaturasSocialesAliadosIndexRoute =
  AuthenticatedDecanaturasSocialesAliadosIndexRouteImport.update({
    id: '/decanaturas/sociales/aliados/',
    path: '/decanaturas/sociales/aliados/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDecanaturasSaludAliadosIndexRoute =
  AuthenticatedDecanaturasSaludAliadosIndexRouteImport.update({
    id: '/decanaturas/salud/aliados/',
    path: '/decanaturas/salud/aliados/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDecanaturasIngenieriasAliadosIndexRoute =
  AuthenticatedDecanaturasIngenieriasAliadosIndexRouteImport.update({
    id: '/decanaturas/ingenierias/aliados/',
    path: '/decanaturas/ingenierias/aliados/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlianzasProyectosAliadosIndexRoute =
  AuthenticatedAlianzasProyectosAliadosIndexRouteImport.update({
    id: '/alianzas/proyectos/aliados/',
    path: '/alianzas/proyectos/aliados/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlianzasMercadeoAliadosIndexRoute =
  AuthenticatedAlianzasMercadeoAliadosIndexRouteImport.update({
    id: '/alianzas/mercadeo/aliados/',
    path: '/alianzas/mercadeo/aliados/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlianzasGraduadosAliadosIndexRoute =
  AuthenticatedAlianzasGraduadosAliadosIndexRouteImport.update({
    id: '/alianzas/graduados/aliados/',
    path: '/alianzas/graduados/aliados/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlianzasEcontiAliadosIndexRoute =
  AuthenticatedAlianzasEcontiAliadosIndexRouteImport.update({
    id: '/alianzas/econti/aliados/',
    path: '/alianzas/econti/aliados/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDecanaturasSocialesAliadosIdRoute =
  AuthenticatedDecanaturasSocialesAliadosIdRouteImport.update({
    id: '/decanaturas/sociales/aliados/$id',
    path: '/decanaturas/sociales/aliados/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDecanaturasSaludAliadosIdRoute =
  AuthenticatedDecanaturasSaludAliadosIdRouteImport.update({
    id: '/decanaturas/salud/aliados/$id',
    path: '/decanaturas/salud/aliados/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDecanaturasIngenieriasAliadosIdRoute =
  AuthenticatedDecanaturasIngenieriasAliadosIdRouteImport.update({
    id: '/decanaturas/ingenierias/aliados/$id',
    path: '/decanaturas/ingenierias/aliados/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlianzasProyectosAliadosIdRoute =
  AuthenticatedAlianzasProyectosAliadosIdRouteImport.update({
    id: '/alianzas/proyectos/aliados/$id',
    path: '/alianzas/proyectos/aliados/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlianzasMercadeoAliadosIdRoute =
  AuthenticatedAlianzasMercadeoAliadosIdRouteImport.update({
    id: '/alianzas/mercadeo/aliados/$id',
    path: '/alianzas/mercadeo/aliados/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlianzasGraduadosAliadosIdRoute =
  AuthenticatedAlianzasGraduadosAliadosIdRouteImport.update({
    id: '/alianzas/graduados/aliados/$id',
    path: '/alianzas/graduados/aliados/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlianzasEcontiAliadosIdRoute =
  AuthenticatedAlianzasEcontiAliadosIdRouteImport.update({
    id: '/alianzas/econti/aliados/$id',
    path: '/alianzas/econti/aliados/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/descuentos': typeof AuthenticatedDescuentosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/aliados/$id': typeof AuthenticatedAliadosIdRoute
  '/alianzas/descuentos': typeof AuthenticatedAlianzasDescuentosRoute
  '/aliados/': typeof AuthenticatedAliadosIndexRoute
  '/alianzas/aliados/$id': typeof AuthenticatedAlianzasAliadosIdRoute
  '/decanaturas/aliados/$id': typeof AuthenticatedDecanaturasAliadosIdRoute
  '/investigacion/aliados/$id': typeof AuthenticatedInvestigacionAliadosIdRoute
  '/proyeccion/aliados/$id': typeof AuthenticatedProyeccionAliadosIdRoute
  '/relaciones-internacionales/aliados/$id': typeof AuthenticatedRelacionesInternacionalesAliadosIdRoute
  '/alianzas/aliados/': typeof AuthenticatedAlianzasAliadosIndexRoute
  '/alianzas/indicadores/': typeof AuthenticatedAlianzasIndicadoresIndexRoute
  '/decanaturas/aliados/': typeof AuthenticatedDecanaturasAliadosIndexRoute
  '/decanaturas/indicadores/': typeof AuthenticatedDecanaturasIndicadoresIndexRoute
  '/investigacion/aliados/': typeof AuthenticatedInvestigacionAliadosIndexRoute
  '/investigacion/indicadores/': typeof AuthenticatedInvestigacionIndicadoresIndexRoute
  '/proyeccion/aliados/': typeof AuthenticatedProyeccionAliadosIndexRoute
  '/proyeccion/indicadores/': typeof AuthenticatedProyeccionIndicadoresIndexRoute
  '/relaciones-internacionales/aliados/': typeof AuthenticatedRelacionesInternacionalesAliadosIndexRoute
  '/relaciones-internacionales/indicadores/': typeof AuthenticatedRelacionesInternacionalesIndicadoresIndexRoute
  '/alianzas/econti/aliados/$id': typeof AuthenticatedAlianzasEcontiAliadosIdRoute
  '/alianzas/graduados/aliados/$id': typeof AuthenticatedAlianzasGraduadosAliadosIdRoute
  '/alianzas/mercadeo/aliados/$id': typeof AuthenticatedAlianzasMercadeoAliadosIdRoute
  '/alianzas/proyectos/aliados/$id': typeof AuthenticatedAlianzasProyectosAliadosIdRoute
  '/decanaturas/ingenierias/aliados/$id': typeof AuthenticatedDecanaturasIngenieriasAliadosIdRoute
  '/decanaturas/salud/aliados/$id': typeof AuthenticatedDecanaturasSaludAliadosIdRoute
  '/decanaturas/sociales/aliados/$id': typeof AuthenticatedDecanaturasSocialesAliadosIdRoute
  '/alianzas/econti/aliados/': typeof AuthenticatedAlianzasEcontiAliadosIndexRoute
  '/alianzas/graduados/aliados/': typeof AuthenticatedAlianzasGraduadosAliadosIndexRoute
  '/alianzas/mercadeo/aliados/': typeof AuthenticatedAlianzasMercadeoAliadosIndexRoute
  '/alianzas/proyectos/aliados/': typeof AuthenticatedAlianzasProyectosAliadosIndexRoute
  '/decanaturas/ingenierias/aliados/': typeof AuthenticatedDecanaturasIngenieriasAliadosIndexRoute
  '/decanaturas/salud/aliados/': typeof AuthenticatedDecanaturasSaludAliadosIndexRoute
  '/decanaturas/sociales/aliados/': typeof AuthenticatedDecanaturasSocialesAliadosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/descuentos': typeof AuthenticatedDescuentosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/aliados/$id': typeof AuthenticatedAliadosIdRoute
  '/alianzas/descuentos': typeof AuthenticatedAlianzasDescuentosRoute
  '/aliados': typeof AuthenticatedAliadosIndexRoute
  '/alianzas/aliados/$id': typeof AuthenticatedAlianzasAliadosIdRoute
  '/decanaturas/aliados/$id': typeof AuthenticatedDecanaturasAliadosIdRoute
  '/investigacion/aliados/$id': typeof AuthenticatedInvestigacionAliadosIdRoute
  '/proyeccion/aliados/$id': typeof AuthenticatedProyeccionAliadosIdRoute
  '/relaciones-internacionales/aliados/$id': typeof AuthenticatedRelacionesInternacionalesAliadosIdRoute
  '/alianzas/aliados': typeof AuthenticatedAlianzasAliadosIndexRoute
  '/alianzas/indicadores': typeof AuthenticatedAlianzasIndicadoresIndexRoute
  '/decanaturas/aliados': typeof AuthenticatedDecanaturasAliadosIndexRoute
  '/decanaturas/indicadores': typeof AuthenticatedDecanaturasIndicadoresIndexRoute
  '/investigacion/aliados': typeof AuthenticatedInvestigacionAliadosIndexRoute
  '/investigacion/indicadores': typeof AuthenticatedInvestigacionIndicadoresIndexRoute
  '/proyeccion/aliados': typeof AuthenticatedProyeccionAliadosIndexRoute
  '/proyeccion/indicadores': typeof AuthenticatedProyeccionIndicadoresIndexRoute
  '/relaciones-internacionales/aliados': typeof AuthenticatedRelacionesInternacionalesAliadosIndexRoute
  '/relaciones-internacionales/indicadores': typeof AuthenticatedRelacionesInternacionalesIndicadoresIndexRoute
  '/alianzas/econti/aliados/$id': typeof AuthenticatedAlianzasEcontiAliadosIdRoute
  '/alianzas/graduados/aliados/$id': typeof AuthenticatedAlianzasGraduadosAliadosIdRoute
  '/alianzas/mercadeo/aliados/$id': typeof AuthenticatedAlianzasMercadeoAliadosIdRoute
  '/alianzas/proyectos/aliados/$id': typeof AuthenticatedAlianzasProyectosAliadosIdRoute
  '/decanaturas/ingenierias/aliados/$id': typeof AuthenticatedDecanaturasIngenieriasAliadosIdRoute
  '/decanaturas/salud/aliados/$id': typeof AuthenticatedDecanaturasSaludAliadosIdRoute
  '/decanaturas/sociales/aliados/$id': typeof AuthenticatedDecanaturasSocialesAliadosIdRoute
  '/alianzas/econti/aliados': typeof AuthenticatedAlianzasEcontiAliadosIndexRoute
  '/alianzas/graduados/aliados': typeof AuthenticatedAlianzasGraduadosAliadosIndexRoute
  '/alianzas/mercadeo/aliados': typeof AuthenticatedAlianzasMercadeoAliadosIndexRoute
  '/alianzas/proyectos/aliados': typeof AuthenticatedAlianzasProyectosAliadosIndexRoute
  '/decanaturas/ingenierias/aliados': typeof AuthenticatedDecanaturasIngenieriasAliadosIndexRoute
  '/decanaturas/salud/aliados': typeof AuthenticatedDecanaturasSaludAliadosIndexRoute
  '/decanaturas/sociales/aliados': typeof AuthenticatedDecanaturasSocialesAliadosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/descuentos': typeof AuthenticatedDescuentosRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/aliados/$id': typeof AuthenticatedAliadosIdRoute
  '/_authenticated/alianzas/descuentos': typeof AuthenticatedAlianzasDescuentosRoute
  '/_authenticated/aliados/': typeof AuthenticatedAliadosIndexRoute
  '/_authenticated/alianzas/aliados/$id': typeof AuthenticatedAlianzasAliadosIdRoute
  '/_authenticated/decanaturas/aliados/$id': typeof AuthenticatedDecanaturasAliadosIdRoute
  '/_authenticated/investigacion/aliados/$id': typeof AuthenticatedInvestigacionAliadosIdRoute
  '/_authenticated/proyeccion/aliados/$id': typeof AuthenticatedProyeccionAliadosIdRoute
  '/_authenticated/relaciones-internacionales/aliados/$id': typeof AuthenticatedRelacionesInternacionalesAliadosIdRoute
  '/_authenticated/alianzas/aliados/': typeof AuthenticatedAlianzasAliadosIndexRoute
  '/_authenticated/alianzas/indicadores/': typeof AuthenticatedAlianzasIndicadoresIndexRoute
  '/_authenticated/decanaturas/aliados/': typeof AuthenticatedDecanaturasAliadosIndexRoute
  '/_authenticated/decanaturas/indicadores/': typeof AuthenticatedDecanaturasIndicadoresIndexRoute
  '/_authenticated/investigacion/aliados/': typeof AuthenticatedInvestigacionAliadosIndexRoute
  '/_authenticated/investigacion/indicadores/': typeof AuthenticatedInvestigacionIndicadoresIndexRoute
  '/_authenticated/proyeccion/aliados/': typeof AuthenticatedProyeccionAliadosIndexRoute
  '/_authenticated/proyeccion/indicadores/': typeof AuthenticatedProyeccionIndicadoresIndexRoute
  '/_authenticated/relaciones-internacionales/aliados/': typeof AuthenticatedRelacionesInternacionalesAliadosIndexRoute
  '/_authenticated/relaciones-internacionales/indicadores/': typeof AuthenticatedRelacionesInternacionalesIndicadoresIndexRoute
  '/_authenticated/alianzas/econti/aliados/$id': typeof AuthenticatedAlianzasEcontiAliadosIdRoute
  '/_authenticated/alianzas/graduados/aliados/$id': typeof AuthenticatedAlianzasGraduadosAliadosIdRoute
  '/_authenticated/alianzas/mercadeo/aliados/$id': typeof AuthenticatedAlianzasMercadeoAliadosIdRoute
  '/_authenticated/alianzas/proyectos/aliados/$id': typeof AuthenticatedAlianzasProyectosAliadosIdRoute
  '/_authenticated/decanaturas/ingenierias/aliados/$id': typeof AuthenticatedDecanaturasIngenieriasAliadosIdRoute
  '/_authenticated/decanaturas/salud/aliados/$id': typeof AuthenticatedDecanaturasSaludAliadosIdRoute
  '/_authenticated/decanaturas/sociales/aliados/$id': typeof AuthenticatedDecanaturasSocialesAliadosIdRoute
  '/_authenticated/alianzas/econti/aliados/': typeof AuthenticatedAlianzasEcontiAliadosIndexRoute
  '/_authenticated/alianzas/graduados/aliados/': typeof AuthenticatedAlianzasGraduadosAliadosIndexRoute
  '/_authenticated/alianzas/mercadeo/aliados/': typeof AuthenticatedAlianzasMercadeoAliadosIndexRoute
  '/_authenticated/alianzas/proyectos/aliados/': typeof AuthenticatedAlianzasProyectosAliadosIndexRoute
  '/_authenticated/decanaturas/ingenierias/aliados/': typeof AuthenticatedDecanaturasIngenieriasAliadosIndexRoute
  '/_authenticated/decanaturas/salud/aliados/': typeof AuthenticatedDecanaturasSaludAliadosIndexRoute
  '/_authenticated/decanaturas/sociales/aliados/': typeof AuthenticatedDecanaturasSocialesAliadosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/descuentos'
    | '/usuarios'
    | '/aliados/$id'
    | '/alianzas/descuentos'
    | '/aliados/'
    | '/alianzas/aliados/$id'
    | '/decanaturas/aliados/$id'
    | '/investigacion/aliados/$id'
    | '/proyeccion/aliados/$id'
    | '/relaciones-internacionales/aliados/$id'
    | '/alianzas/aliados/'
    | '/alianzas/indicadores/'
    | '/decanaturas/aliados/'
    | '/decanaturas/indicadores/'
    | '/investigacion/aliados/'
    | '/investigacion/indicadores/'
    | '/proyeccion/aliados/'
    | '/proyeccion/indicadores/'
    | '/relaciones-internacionales/aliados/'
    | '/relaciones-internacionales/indicadores/'
    | '/alianzas/econti/aliados/$id'
    | '/alianzas/graduados/aliados/$id'
    | '/alianzas/mercadeo/aliados/$id'
    | '/alianzas/proyectos/aliados/$id'
    | '/decanaturas/ingenierias/aliados/$id'
    | '/decanaturas/salud/aliados/$id'
    | '/decanaturas/sociales/aliados/$id'
    | '/alianzas/econti/aliados/'
    | '/alianzas/graduados/aliados/'
    | '/alianzas/mercadeo/aliados/'
    | '/alianzas/proyectos/aliados/'
    | '/decanaturas/ingenierias/aliados/'
    | '/decanaturas/salud/aliados/'
    | '/decanaturas/sociales/aliados/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/descuentos'
    | '/usuarios'
    | '/aliados/$id'
    | '/alianzas/descuentos'
    | '/aliados'
    | '/alianzas/aliados/$id'
    | '/decanaturas/aliados/$id'
    | '/investigacion/aliados/$id'
    | '/proyeccion/aliados/$id'
    | '/relaciones-internacionales/aliados/$id'
    | '/alianzas/aliados'
    | '/alianzas/indicadores'
    | '/decanaturas/aliados'
    | '/decanaturas/indicadores'
    | '/investigacion/aliados'
    | '/investigacion/indicadores'
    | '/proyeccion/aliados'
    | '/proyeccion/indicadores'
    | '/relaciones-internacionales/aliados'
    | '/relaciones-internacionales/indicadores'
    | '/alianzas/econti/aliados/$id'
    | '/alianzas/graduados/aliados/$id'
    | '/alianzas/mercadeo/aliados/$id'
    | '/alianzas/proyectos/aliados/$id'
    | '/decanaturas/ingenierias/aliados/$id'
    | '/decanaturas/salud/aliados/$id'
    | '/decanaturas/sociales/aliados/$id'
    | '/alianzas/econti/aliados'
    | '/alianzas/graduados/aliados'
    | '/alianzas/mercadeo/aliados'
    | '/alianzas/proyectos/aliados'
    | '/decanaturas/ingenierias/aliados'
    | '/decanaturas/salud/aliados'
    | '/decanaturas/sociales/aliados'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/descuentos'
    | '/_authenticated/usuarios'
    | '/_authenticated/aliados/$id'
    | '/_authenticated/alianzas/descuentos'
    | '/_authenticated/aliados/'
    | '/_authenticated/alianzas/aliados/$id'
    | '/_authenticated/decanaturas/aliados/$id'
    | '/_authenticated/investigacion/aliados/$id'
    | '/_authenticated/proyeccion/aliados/$id'
    | '/_authenticated/relaciones-internacionales/aliados/$id'
    | '/_authenticated/alianzas/aliados/'
    | '/_authenticated/alianzas/indicadores/'
    | '/_authenticated/decanaturas/aliados/'
    | '/_authenticated/decanaturas/indicadores/'
    | '/_authenticated/investigacion/aliados/'
    | '/_authenticated/investigacion/indicadores/'
    | '/_authenticated/proyeccion/aliados/'
    | '/_authenticated/proyeccion/indicadores/'
    | '/_authenticated/relaciones-internacionales/aliados/'
    | '/_authenticated/relaciones-internacionales/indicadores/'
    | '/_authenticated/alianzas/econti/aliados/$id'
    | '/_authenticated/alianzas/graduados/aliados/$id'
    | '/_authenticated/alianzas/mercadeo/aliados/$id'
    | '/_authenticated/alianzas/proyectos/aliados/$id'
    | '/_authenticated/decanaturas/ingenierias/aliados/$id'
    | '/_authenticated/decanaturas/salud/aliados/$id'
    | '/_authenticated/decanaturas/sociales/aliados/$id'
    | '/_authenticated/alianzas/econti/aliados/'
    | '/_authenticated/alianzas/graduados/aliados/'
    | '/_authenticated/alianzas/mercadeo/aliados/'
    | '/_authenticated/alianzas/proyectos/aliados/'
    | '/_authenticated/decanaturas/ingenierias/aliados/'
    | '/_authenticated/decanaturas/salud/aliados/'
    | '/_authenticated/decanaturas/sociales/aliados/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/descuentos': {
      id: '/_authenticated/descuentos'
      path: '/descuentos'
      fullPath: '/descuentos'
      preLoaderRoute: typeof AuthenticatedDescuentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aliados/': {
      id: '/_authenticated/aliados/'
      path: '/aliados'
      fullPath: '/aliados/'
      preLoaderRoute: typeof AuthenticatedAliadosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alianzas/descuentos': {
      id: '/_authenticated/alianzas/descuentos'
      path: '/alianzas/descuentos'
      fullPath: '/alianzas/descuentos'
      preLoaderRoute: typeof AuthenticatedAlianzasDescuentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aliados/$id': {
      id: '/_authenticated/aliados/$id'
      path: '/aliados/$id'
      fullPath: '/aliados/$id'
      preLoaderRoute: typeof AuthenticatedAliadosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relaciones-internacionales/indicadores/': {
      id: '/_authenticated/relaciones-internacionales/indicadores/'
      path: '/relaciones-internacionales/indicadores'
      fullPath: '/relaciones-internacionales/indicadores/'
      preLoaderRoute: typeof AuthenticatedRelacionesInternacionalesIndicadoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relaciones-internacionales/aliados/': {
      id: '/_authenticated/relaciones-internacionales/aliados/'
      path: '/relaciones-internacionales/aliados'
      fullPath: '/relaciones-internacionales/aliados/'
      preLoaderRoute: typeof AuthenticatedRelacionesInternacionalesAliadosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proyeccion/indicadores/': {
      id: '/_authenticated/proyeccion/indicadores/'
      path: '/proyeccion/indicadores'
      fullPath: '/proyeccion/indicadores/'
      preLoaderRoute: typeof AuthenticatedProyeccionIndicadoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proyeccion/aliados/': {
      id: '/_authenticated/proyeccion/aliados/'
      path: '/proyeccion/aliados'
      fullPath: '/proyeccion/aliados/'
      preLoaderRoute: typeof AuthenticatedProyeccionAliadosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investigacion/indicadores/': {
      id: '/_authenticated/investigacion/indicadores/'
      path: '/investigacion/indicadores'
      fullPath: '/investigacion/indicadores/'
      preLoaderRoute: typeof AuthenticatedInvestigacionIndicadoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investigacion/aliados/': {
      id: '/_authenticated/investigacion/aliados/'
      path: '/investigacion/aliados'
      fullPath: '/investigacion/aliados/'
      preLoaderRoute: typeof AuthenticatedInvestigacionAliadosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/decanaturas/indicadores/': {
      id: '/_authenticated/decanaturas/indicadores/'
      path: '/decanaturas/indicadores'
      fullPath: '/decanaturas/indicadores/'
      preLoaderRoute: typeof AuthenticatedDecanaturasIndicadoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/decanaturas/aliados/': {
      id: '/_authenticated/decanaturas/aliados/'
      path: '/decanaturas/aliados'
      fullPath: '/decanaturas/aliados/'
      preLoaderRoute: typeof AuthenticatedDecanaturasAliadosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alianzas/indicadores/': {
      id: '/_authenticated/alianzas/indicadores/'
      path: '/alianzas/indicadores'
      fullPath: '/alianzas/indicadores/'
      preLoaderRoute: typeof AuthenticatedAlianzasIndicadoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alianzas/aliados/': {
      id: '/_authenticated/alianzas/aliados/'
      path: '/alianzas/aliados'
      fullPath: '/alianzas/aliados/'
      preLoaderRoute: typeof AuthenticatedAlianzasAliadosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relaciones-internacionales/aliados/$id': {
      id: '/_authenticated/relaciones-internacionales/aliados/$id'
      path: '/relaciones-internacionales/aliados/$id'
      fullPath: '/relaciones-internacionales/aliados/$id'
      preLoaderRoute: typeof AuthenticatedRelacionesInternacionalesAliadosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proyeccion/aliados/$id': {
      id: '/_authenticated/proyeccion/aliados/$id'
      path: '/proyeccion/aliados/$id'
      fullPath: '/proyeccion/aliados/$id'
      preLoaderRoute: typeof AuthenticatedProyeccionAliadosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investigacion/aliados/$id': {
      id: '/_authenticated/investigacion/aliados/$id'
      path: '/investigacion/aliados/$id'
      fullPath: '/investigacion/aliados/$id'
      preLoaderRoute: typeof AuthenticatedInvestigacionAliadosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/decanaturas/aliados/$id': {
      id: '/_authenticated/decanaturas/aliados/$id'
      path: '/decanaturas/aliados/$id'
      fullPath: '/decanaturas/aliados/$id'
      preLoaderRoute: typeof AuthenticatedDecanaturasAliadosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alianzas/aliados/$id': {
      id: '/_authenticated/alianzas/aliados/$id'
      path: '/alianzas/aliados/$id'
      fullPath: '/alianzas/aliados/$id'
      preLoaderRoute: typeof AuthenticatedAlianzasAliadosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/decanaturas/sociales/aliados/': {
      id: '/_authenticated/decanaturas/sociales/aliados/'
      path: '/decanaturas/sociales/aliados'
      fullPath: '/decanaturas/sociales/aliados/'
      preLoaderRoute: typeof AuthenticatedDecanaturasSocialesAliadosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/decanaturas/salud/aliados/': {
      id: '/_authenticated/decanaturas/salud/aliados/'
      path: '/decanaturas/salud/aliados'
      fullPath: '/decanaturas/salud/aliados/'
      preLoaderRoute: typeof AuthenticatedDecanaturasSaludAliadosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/decanaturas/ingenierias/aliados/': {
      id: '/_authenticated/decanaturas/ingenierias/aliados/'
      path: '/decanaturas/ingenierias/aliados'
      fullPath: '/decanaturas/ingenierias/aliados/'
      preLoaderRoute: typeof AuthenticatedDecanaturasIngenieriasAliadosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alianzas/proyectos/aliados/': {
      id: '/_authenticated/alianzas/proyectos/aliados/'
      path: '/alianzas/proyectos/aliados'
      fullPath: '/alianzas/proyectos/aliados/'
      preLoaderRoute: typeof AuthenticatedAlianzasProyectosAliadosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alianzas/mercadeo/aliados/': {
      id: '/_authenticated/alianzas/mercadeo/aliados/'
      path: '/alianzas/mercadeo/aliados'
      fullPath: '/alianzas/mercadeo/aliados/'
      preLoaderRoute: typeof AuthenticatedAlianzasMercadeoAliadosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alianzas/graduados/aliados/': {
      id: '/_authenticated/alianzas/graduados/aliados/'
      path: '/alianzas/graduados/aliados'
      fullPath: '/alianzas/graduados/aliados/'
      preLoaderRoute: typeof AuthenticatedAlianzasGraduadosAliadosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alianzas/econti/aliados/': {
      id: '/_authenticated/alianzas/econti/aliados/'
      path: '/alianzas/econti/aliados'
      fullPath: '/alianzas/econti/aliados/'
      preLoaderRoute: typeof AuthenticatedAlianzasEcontiAliadosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/decanaturas/sociales/aliados/$id': {
      id: '/_authenticated/decanaturas/sociales/aliados/$id'
      path: '/decanaturas/sociales/aliados/$id'
      fullPath: '/decanaturas/sociales/aliados/$id'
      preLoaderRoute: typeof AuthenticatedDecanaturasSocialesAliadosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/decanaturas/salud/aliados/$id': {
      id: '/_authenticated/decanaturas/salud/aliados/$id'
      path: '/decanaturas/salud/aliados/$id'
      fullPath: '/decanaturas/salud/aliados/$id'
      preLoaderRoute: typeof AuthenticatedDecanaturasSaludAliadosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/decanaturas/ingenierias/aliados/$id': {
      id: '/_authenticated/decanaturas/ingenierias/aliados/$id'
      path: '/decanaturas/ingenierias/aliados/$id'
      fullPath: '/decanaturas/ingenierias/aliados/$id'
      preLoaderRoute: typeof AuthenticatedDecanaturasIngenieriasAliadosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alianzas/proyectos/aliados/$id': {
      id: '/_authenticated/alianzas/proyectos/aliados/$id'
      path: '/alianzas/proyectos/aliados/$id'
      fullPath: '/alianzas/proyectos/aliados/$id'
      preLoaderRoute: typeof AuthenticatedAlianzasProyectosAliadosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alianzas/mercadeo/aliados/$id': {
      id: '/_authenticated/alianzas/mercadeo/aliados/$id'
      path: '/alianzas/mercadeo/aliados/$id'
      fullPath: '/alianzas/mercadeo/aliados/$id'
      preLoaderRoute: typeof AuthenticatedAlianzasMercadeoAliadosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alianzas/graduados/aliados/$id': {
      id: '/_authenticated/alianzas/graduados/aliados/$id'
      path: '/alianzas/graduados/aliados/$id'
      fullPath: '/alianzas/graduados/aliados/$id'
      preLoaderRoute: typeof AuthenticatedAlianzasGraduadosAliadosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alianzas/econti/aliados/$id': {
      id: '/_authenticated/alianzas/econti/aliados/$id'
      path: '/alianzas/econti/aliados/$id'
      fullPath: '/alianzas/econti/aliados/$id'
      preLoaderRoute: typeof AuthenticatedAlianzasEcontiAliadosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDescuentosRoute: typeof AuthenticatedDescuentosRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedAliadosIdRoute: typeof AuthenticatedAliadosIdRoute
  AuthenticatedAlianzasDescuentosRoute: typeof AuthenticatedAlianzasDescuentosRoute
  AuthenticatedAliadosIndexRoute: typeof AuthenticatedAliadosIndexRoute
  AuthenticatedAlianzasAliadosIdRoute: typeof AuthenticatedAlianzasAliadosIdRoute
  AuthenticatedDecanaturasAliadosIdRoute: typeof AuthenticatedDecanaturasAliadosIdRoute
  AuthenticatedInvestigacionAliadosIdRoute: typeof AuthenticatedInvestigacionAliadosIdRoute
  AuthenticatedProyeccionAliadosIdRoute: typeof AuthenticatedProyeccionAliadosIdRoute
  AuthenticatedRelacionesInternacionalesAliadosIdRoute: typeof AuthenticatedRelacionesInternacionalesAliadosIdRoute
  AuthenticatedAlianzasAliadosIndexRoute: typeof AuthenticatedAlianzasAliadosIndexRoute
  AuthenticatedAlianzasIndicadoresIndexRoute: typeof AuthenticatedAlianzasIndicadoresIndexRoute
  AuthenticatedDecanaturasAliadosIndexRoute: typeof AuthenticatedDecanaturasAliadosIndexRoute
  AuthenticatedDecanaturasIndicadoresIndexRoute: typeof AuthenticatedDecanaturasIndicadoresIndexRoute
  AuthenticatedInvestigacionAliadosIndexRoute: typeof AuthenticatedInvestigacionAliadosIndexRoute
  AuthenticatedInvestigacionIndicadoresIndexRoute: typeof AuthenticatedInvestigacionIndicadoresIndexRoute
  AuthenticatedProyeccionAliadosIndexRoute: typeof AuthenticatedProyeccionAliadosIndexRoute
  AuthenticatedProyeccionIndicadoresIndexRoute: typeof AuthenticatedProyeccionIndicadoresIndexRoute
  AuthenticatedRelacionesInternacionalesAliadosIndexRoute: typeof AuthenticatedRelacionesInternacionalesAliadosIndexRoute
  AuthenticatedRelacionesInternacionalesIndicadoresIndexRoute: typeof AuthenticatedRelacionesInternacionalesIndicadoresIndexRoute
  AuthenticatedAlianzasEcontiAliadosIdRoute: typeof AuthenticatedAlianzasEcontiAliadosIdRoute
  AuthenticatedAlianzasGraduadosAliadosIdRoute: typeof AuthenticatedAlianzasGraduadosAliadosIdRoute
  AuthenticatedAlianzasMercadeoAliadosIdRoute: typeof AuthenticatedAlianzasMercadeoAliadosIdRoute
  AuthenticatedAlianzasProyectosAliadosIdRoute: typeof AuthenticatedAlianzasProyectosAliadosIdRoute
  AuthenticatedDecanaturasIngenieriasAliadosIdRoute: typeof AuthenticatedDecanaturasIngenieriasAliadosIdRoute
  AuthenticatedDecanaturasSaludAliadosIdRoute: typeof AuthenticatedDecanaturasSaludAliadosIdRoute
  AuthenticatedDecanaturasSocialesAliadosIdRoute: typeof AuthenticatedDecanaturasSocialesAliadosIdRoute
  AuthenticatedAlianzasEcontiAliadosIndexRoute: typeof AuthenticatedAlianzasEcontiAliadosIndexRoute
  AuthenticatedAlianzasGraduadosAliadosIndexRoute: typeof AuthenticatedAlianzasGraduadosAliadosIndexRoute
  AuthenticatedAlianzasMercadeoAliadosIndexRoute: typeof AuthenticatedAlianzasMercadeoAliadosIndexRoute
  AuthenticatedAlianzasProyectosAliadosIndexRoute: typeof AuthenticatedAlianzasProyectosAliadosIndexRoute
  AuthenticatedDecanaturasIngenieriasAliadosIndexRoute: typeof AuthenticatedDecanaturasIngenieriasAliadosIndexRoute
  AuthenticatedDecanaturasSaludAliadosIndexRoute: typeof AuthenticatedDecanaturasSaludAliadosIndexRoute
  AuthenticatedDecanaturasSocialesAliadosIndexRoute: typeof AuthenticatedDecanaturasSocialesAliadosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDescuentosRoute: AuthenticatedDescuentosRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedAliadosIdRoute: AuthenticatedAliadosIdRoute,
  AuthenticatedAlianzasDescuentosRoute: AuthenticatedAlianzasDescuentosRoute,
  AuthenticatedAliadosIndexRoute: AuthenticatedAliadosIndexRoute,
  AuthenticatedAlianzasAliadosIdRoute: AuthenticatedAlianzasAliadosIdRoute,
  AuthenticatedDecanaturasAliadosIdRoute:
    AuthenticatedDecanaturasAliadosIdRoute,
  AuthenticatedInvestigacionAliadosIdRoute:
    AuthenticatedInvestigacionAliadosIdRoute,
  AuthenticatedProyeccionAliadosIdRoute: AuthenticatedProyeccionAliadosIdRoute,
  AuthenticatedRelacionesInternacionalesAliadosIdRoute:
    AuthenticatedRelacionesInternacionalesAliadosIdRoute,
  AuthenticatedAlianzasAliadosIndexRoute:
    AuthenticatedAlianzasAliadosIndexRoute,
  AuthenticatedAlianzasIndicadoresIndexRoute:
    AuthenticatedAlianzasIndicadoresIndexRoute,
  AuthenticatedDecanaturasAliadosIndexRoute:
    AuthenticatedDecanaturasAliadosIndexRoute,
  AuthenticatedDecanaturasIndicadoresIndexRoute:
    AuthenticatedDecanaturasIndicadoresIndexRoute,
  AuthenticatedInvestigacionAliadosIndexRoute:
    AuthenticatedInvestigacionAliadosIndexRoute,
  AuthenticatedInvestigacionIndicadoresIndexRoute:
    AuthenticatedInvestigacionIndicadoresIndexRoute,
  AuthenticatedProyeccionAliadosIndexRoute:
    AuthenticatedProyeccionAliadosIndexRoute,
  AuthenticatedProyeccionIndicadoresIndexRoute:
    AuthenticatedProyeccionIndicadoresIndexRoute,
  AuthenticatedRelacionesInternacionalesAliadosIndexRoute:
    AuthenticatedRelacionesInternacionalesAliadosIndexRoute,
  AuthenticatedRelacionesInternacionalesIndicadoresIndexRoute:
    AuthenticatedRelacionesInternacionalesIndicadoresIndexRoute,
  AuthenticatedAlianzasEcontiAliadosIdRoute:
    AuthenticatedAlianzasEcontiAliadosIdRoute,
  AuthenticatedAlianzasGraduadosAliadosIdRoute:
    AuthenticatedAlianzasGraduadosAliadosIdRoute,
  AuthenticatedAlianzasMercadeoAliadosIdRoute:
    AuthenticatedAlianzasMercadeoAliadosIdRoute,
  AuthenticatedAlianzasProyectosAliadosIdRoute:
    AuthenticatedAlianzasProyectosAliadosIdRoute,
  AuthenticatedDecanaturasIngenieriasAliadosIdRoute:
    AuthenticatedDecanaturasIngenieriasAliadosIdRoute,
  AuthenticatedDecanaturasSaludAliadosIdRoute:
    AuthenticatedDecanaturasSaludAliadosIdRoute,
  AuthenticatedDecanaturasSocialesAliadosIdRoute:
    AuthenticatedDecanaturasSocialesAliadosIdRoute,
  AuthenticatedAlianzasEcontiAliadosIndexRoute:
    AuthenticatedAlianzasEcontiAliadosIndexRoute,
  AuthenticatedAlianzasGraduadosAliadosIndexRoute:
    AuthenticatedAlianzasGraduadosAliadosIndexRoute,
  AuthenticatedAlianzasMercadeoAliadosIndexRoute:
    AuthenticatedAlianzasMercadeoAliadosIndexRoute,
  AuthenticatedAlianzasProyectosAliadosIndexRoute:
    AuthenticatedAlianzasProyectosAliadosIndexRoute,
  AuthenticatedDecanaturasIngenieriasAliadosIndexRoute:
    AuthenticatedDecanaturasIngenieriasAliadosIndexRoute,
  AuthenticatedDecanaturasSaludAliadosIndexRoute:
    AuthenticatedDecanaturasSaludAliadosIndexRoute,
  AuthenticatedDecanaturasSocialesAliadosIndexRoute:
    AuthenticatedDecanaturasSocialesAliadosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
