/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedDescuentosRouteImport } from './routes/_authenticated/descuentos'
import { Route as AuthenticatedAliadosIndexRouteImport } from './routes/_authenticated/aliados/index'
import { Route as AuthenticatedAliadosIdRouteImport } from './routes/_authenticated/aliados/$id'
import { Route as AuthenticatedInvestigacionAliadosIndexRouteImport } from './routes/_authenticated/investigacion/aliados/index'
import { Route as AuthenticatedAlianzasAliadosIndexRouteImport } from './routes/_authenticated/alianzas/aliados/index'
import { Route as AuthenticatedInvestigacionAliadosIdRouteImport } from './routes/_authenticated/investigacion/aliados/$id'
import { Route as AuthenticatedAlianzasAliadosIdRouteImport } from './routes/_authenticated/alianzas/aliados/$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDescuentosRoute = AuthenticatedDescuentosRouteImport.update({
  id: '/descuentos',
  path: '/descuentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAliadosIndexRoute =
  AuthenticatedAliadosIndexRouteImport.update({
    id: '/aliados/',
    path: '/aliados/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAliadosIdRoute = AuthenticatedAliadosIdRouteImport.update({
  id: '/aliados/$id',
  path: '/aliados/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvestigacionAliadosIndexRoute =
  AuthenticatedInvestigacionAliadosIndexRouteImport.update({
    id: '/investigacion/aliados/',
    path: '/investigacion/aliados/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlianzasAliadosIndexRoute =
  AuthenticatedAlianzasAliadosIndexRouteImport.update({
    id: '/alianzas/aliados/',
    path: '/alianzas/aliados/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestigacionAliadosIdRoute =
  AuthenticatedInvestigacionAliadosIdRouteImport.update({
    id: '/investigacion/aliados/$id',
    path: '/investigacion/aliados/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlianzasAliadosIdRoute =
  AuthenticatedAlianzasAliadosIdRouteImport.update({
    id: '/alianzas/aliados/$id',
    path: '/alianzas/aliados/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/descuentos': typeof AuthenticatedDescuentosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/aliados/$id': typeof AuthenticatedAliadosIdRoute
  '/aliados/': typeof AuthenticatedAliadosIndexRoute
  '/alianzas/aliados/$id': typeof AuthenticatedAlianzasAliadosIdRoute
  '/investigacion/aliados/$id': typeof AuthenticatedInvestigacionAliadosIdRoute
  '/alianzas/aliados/': typeof AuthenticatedAlianzasAliadosIndexRoute
  '/investigacion/aliados/': typeof AuthenticatedInvestigacionAliadosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/descuentos': typeof AuthenticatedDescuentosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/aliados/$id': typeof AuthenticatedAliadosIdRoute
  '/aliados': typeof AuthenticatedAliadosIndexRoute
  '/alianzas/aliados/$id': typeof AuthenticatedAlianzasAliadosIdRoute
  '/investigacion/aliados/$id': typeof AuthenticatedInvestigacionAliadosIdRoute
  '/alianzas/aliados': typeof AuthenticatedAlianzasAliadosIndexRoute
  '/investigacion/aliados': typeof AuthenticatedInvestigacionAliadosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/descuentos': typeof AuthenticatedDescuentosRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/aliados/$id': typeof AuthenticatedAliadosIdRoute
  '/_authenticated/aliados/': typeof AuthenticatedAliadosIndexRoute
  '/_authenticated/alianzas/aliados/$id': typeof AuthenticatedAlianzasAliadosIdRoute
  '/_authenticated/investigacion/aliados/$id': typeof AuthenticatedInvestigacionAliadosIdRoute
  '/_authenticated/alianzas/aliados/': typeof AuthenticatedAlianzasAliadosIndexRoute
  '/_authenticated/investigacion/aliados/': typeof AuthenticatedInvestigacionAliadosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/descuentos'
    | '/usuarios'
    | '/aliados/$id'
    | '/aliados/'
    | '/alianzas/aliados/$id'
    | '/investigacion/aliados/$id'
    | '/alianzas/aliados/'
    | '/investigacion/aliados/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/descuentos'
    | '/usuarios'
    | '/aliados/$id'
    | '/aliados'
    | '/alianzas/aliados/$id'
    | '/investigacion/aliados/$id'
    | '/alianzas/aliados'
    | '/investigacion/aliados'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/descuentos'
    | '/_authenticated/usuarios'
    | '/_authenticated/aliados/$id'
    | '/_authenticated/aliados/'
    | '/_authenticated/alianzas/aliados/$id'
    | '/_authenticated/investigacion/aliados/$id'
    | '/_authenticated/alianzas/aliados/'
    | '/_authenticated/investigacion/aliados/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/descuentos': {
      id: '/_authenticated/descuentos'
      path: '/descuentos'
      fullPath: '/descuentos'
      preLoaderRoute: typeof AuthenticatedDescuentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aliados/': {
      id: '/_authenticated/aliados/'
      path: '/aliados'
      fullPath: '/aliados/'
      preLoaderRoute: typeof AuthenticatedAliadosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aliados/$id': {
      id: '/_authenticated/aliados/$id'
      path: '/aliados/$id'
      fullPath: '/aliados/$id'
      preLoaderRoute: typeof AuthenticatedAliadosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investigacion/aliados/': {
      id: '/_authenticated/investigacion/aliados/'
      path: '/investigacion/aliados'
      fullPath: '/investigacion/aliados/'
      preLoaderRoute: typeof AuthenticatedInvestigacionAliadosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alianzas/aliados/': {
      id: '/_authenticated/alianzas/aliados/'
      path: '/alianzas/aliados'
      fullPath: '/alianzas/aliados/'
      preLoaderRoute: typeof AuthenticatedAlianzasAliadosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investigacion/aliados/$id': {
      id: '/_authenticated/investigacion/aliados/$id'
      path: '/investigacion/aliados/$id'
      fullPath: '/investigacion/aliados/$id'
      preLoaderRoute: typeof AuthenticatedInvestigacionAliadosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alianzas/aliados/$id': {
      id: '/_authenticated/alianzas/aliados/$id'
      path: '/alianzas/aliados/$id'
      fullPath: '/alianzas/aliados/$id'
      preLoaderRoute: typeof AuthenticatedAlianzasAliadosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDescuentosRoute: typeof AuthenticatedDescuentosRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedAliadosIdRoute: typeof AuthenticatedAliadosIdRoute
  AuthenticatedAliadosIndexRoute: typeof AuthenticatedAliadosIndexRoute
  AuthenticatedAlianzasAliadosIdRoute: typeof AuthenticatedAlianzasAliadosIdRoute
  AuthenticatedInvestigacionAliadosIdRoute: typeof AuthenticatedInvestigacionAliadosIdRoute
  AuthenticatedAlianzasAliadosIndexRoute: typeof AuthenticatedAlianzasAliadosIndexRoute
  AuthenticatedInvestigacionAliadosIndexRoute: typeof AuthenticatedInvestigacionAliadosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDescuentosRoute: AuthenticatedDescuentosRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedAliadosIdRoute: AuthenticatedAliadosIdRoute,
  AuthenticatedAliadosIndexRoute: AuthenticatedAliadosIndexRoute,
  AuthenticatedAlianzasAliadosIdRoute: AuthenticatedAlianzasAliadosIdRoute,
  AuthenticatedInvestigacionAliadosIdRoute:
    AuthenticatedInvestigacionAliadosIdRoute,
  AuthenticatedAlianzasAliadosIndexRoute:
    AuthenticatedAlianzasAliadosIndexRoute,
  AuthenticatedInvestigacionAliadosIndexRoute:
    AuthenticatedInvestigacionAliadosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
